### DISCUSSION TITLE
Need help configuring vite with Docker/Compose, code changes to JS needs a container restart

### DISCUSSION THREAD

**Discussion by zgmrvn** [ElMassimo/vite_ruby#207] [Q&A]
I've been trying to run a Rails 7/Inertia.js/Vue app for days, both Rails and Vite are started by Foreman. The whole thing runs in a single Docker container. The code is properly compiled when I start the container but if I want my changes to take effect I need to restart the container, refreshing the page doesn't work (since the front is in a Vue component).

 docker-compose.yml
```yml
version: '3.9'

services:
  db:
    ...
  
  app:
    build: .
    container_name: udb_app
    command: foreman start
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - 3000:3000
      - 3036:3036
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
```

.foreman
```
procfile: Procfile.dev
```

Procfile.dev
```
web: bundle exec rails server -p 3000 -b '0.0.0.0'
vite: bundle exec vite dev
```

vite.json
```json
{
  "all": {
    "sourceCodeDir": "app/frontend",
    "entrypointsDir": "entrypoints",
    "watchAdditionalPaths": []
  },
  "development": {
    "autoBuild": true,
    "publicOutputDir": "vite-dev",
    "port": 3036
  },
  "test": {
    "autoBuild": true,
    "publicOutputDir": "vite-test",
    "port": 3037
  }
}
```
The terminal when I run `docker-compose up`
![image](https://user-images.githubusercontent.com/3134449/164982925-629d9037-e03d-4517-b55e-338d26f7a709.png)

Chrome console
![image](https://user-images.githubusercontent.com/3134449/164982981-6a6ef56e-356b-42a8-ac33-7f51c3fbb013.png)

Chrome WS networking
![image](https://user-images.githubusercontent.com/3134449/164983549-41106e1f-1ee5-438b-921c-4eb29f69d828.png)

Has anyone ever managed to run Rails 7 and Vite through Foreman ?

**Comment by ElMassimo** [comment]
If you need to restart the container for changes to take effect, it's likely that you are not mounting the source code dirs correctly, so the image needs to be rebuilt in order for changes to be picked up.

I'd recommend reading [this _Dockerizing Rails_ guide](https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development?utm_source=twitter.com&utm_medium=social&utm_campaign=attention-all-rails-docker-users!-we-hav). It should be simple to adapt the webpacker steps for Vite Rails, and it will ensure that volumes are mounted in a way that changes don't require restarting your server.

**Comment by zgmrvn** [comment]
Thanks for the documentation, however, it didn't help. Totally desperate, I ended up just copying the docker-compose.yml of [this exemple](https://github.com/ElMassimo/vite_rails_docker_example) linked in the documentation, the only difference is I use the Vue plugin in addition, and still, it **does not work**, no HMR, no change on page refresh, only the build when the container starts.

```yml
version: '3.9'

services:
  db:
   # ...
  
  app:
    build: .
    container_name: udb_app
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: vite

  vite:
    build: .
    container_name: udb_vite
    entrypoint: ./docker-vite.sh
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - 3036:3036
    volumes:
      - .:/myapp
```
```js
import { defineConfig } from 'vite'
import RubyPlugin from 'vite-plugin-ruby'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    RubyPlugin(),
    vue()
  ]
})
```
Everything is working fine if I just run `foreman start` directly from my terminal, but as soon as it's in a container, it doesn't work
