### DISCUSSION TITLE
How to test(Rspec capybara + selenium) with docker selenium container

### DISCUSSION THREAD

**Discussion by y-hikaru-walabo** [ElMassimo/vite_ruby#304] [Q&A]
My application five containers are running.
- App container
- App_test container
- db container
- vite container
- seleniarm container

The steps I will now test are as follows
1. Enter vite container
2. exec command `RAILS_ENV=test bin/vite build`
3. Enter App_test container
4. exec command `bundle exec rspec`

It is time consuming to build every time I do a test.
Running the test without building will result in an error.
```
Failure/Error: =vite_javascript_tag '/webpack/entrypoint/application.ts'    
ActionView::Template::Error:
Vite Ruby can't find entrypoint/application.ts in public/vite-test/manifest.json or public/vite-test/manifest-assets.json.    
Possible causes:
  - The last build failed. Try running `bin/vite build --clear --mode=test` manually and check for errors.
Errors:
  env: can't execute 'node': No such file or directory
```

The settings are as follows

vite.json
```json
{
  "all": {
    "sourceCodeDir": "webpack",
    "entrypointsDir": "entrypoint",
    "watchAdditionalPaths": [],
    "additionalEntrypoints": ["webpack/js/pages/**/**/entry.tsx"]
  },
  "development": {
    "autoBuild": true,
    "publicOutputDir": "vite-dev",
    "port": 3036
  },
  "test": {
    "autoBuild": true,
    "publicOutputDir": "vite-test",
    "port": 3037
  }
}

```
docker-compose.yml
```yml
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: development
    volumes:
      - ./project_src:/var/www
    environment:
      VITE_RUBY_HOST: vite
      RAILS_ENV: development
    ports:
      - 60000:3000
    depends_on:
      - vite
      - selenium_chrome

  app_test:
    volumes:
      - ./project_src:/var/www
    environment:
      RAILS_ENV: test
    depends_on:
      - selenium_chrome

  vite:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: development
    environment:
      DEBUG: "*vite*"
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - ./project_src:/var/www/
    command: >
      /bin/bash -c "
        yarn && bin/vite dev
      "

  selenium_chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 5900:5900
```

Let me know if you know how to test it without doing a build.

vite-plugin-ruby 3.1.2
vite 3.2.2
Ruby 3.0.3
Rails 7.0.4
