### DISCUSSION TITLE
Vite runs on development but fails on production

### DISCUSSION THREAD

**Discussion by rockwellll** [ElMassimo/vite_ruby#389] [Q&A] [answered]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Hi, hoping you're having a good day. I've setup vite-rails for my application. Everything runs okay in development, however, when pushing the app to production. The build fails and i get this error,

```
ViteRuby::MissingEntrypointError
Vite Ruby can't find entrypoints/application.js in public/vite/manifest.json or public/vite/manifest-assets.json.

Possible causes:
  - The file path is incorrect.
  - The file is not in the entrypoints directory.
  - Some files are outside the sourceCodeDir, and have not been added to watchAdditionalPaths.
  - You have not run `bin/vite dev` to start Vite, or the dev server is not reachable.
  - "autoBuild" is set to `false` in your config/vite.json for this environment.

Visit the Troubleshooting guide for more information:
  https://vite-ruby.netlify.app/guide/troubleshooting.html#troubleshooting
```

I have read everywhere on the documentation but could not solve this. Anything would really help. 

Thank you

**Comment by ElMassimo** [comment]
Hi Ahmed!

> The build fails

Please provide a trace of how the build fails. In most deployment configurations, if the build step fails, the deployment would be aborted.

> and i get this error

Based on the error message, it looks like `vite:build` (or `assets:precompile`) was not run on deployment.

If the build actually run and failed, the error message would explicitly mention [`The last build failed`](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/missing_entrypoint_error.rb#L24C1-L41).

Verify that `public/vite` exists and contains the expected files (`manifest.json` and an `assets` dir).

**Comment by rockwellll** [comment]
Hi, thank you for your fast response! Much needed!

We're using a Dockerfile that runs `asset:precompile` and deployed using K8.'

> Please provide a trace of how the build fails. In most deployment configurations, if the build step fails, the deployment would be aborted.

The pods are deployed but never started because of the error above. Sorry, i did not understand your question. 

> Verify that public/vite exists and contains the expected files (manifest.json and an assets dir).

I've been looking into it and there's a `public/vite-dev` directory but no `public/vite`. I tried running the command `bin/vite build` inside the pod and i got this error,


```
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa3ad50 node::Abort() [node]
 2: 0x970199 node::FatalError(char const*, char const*) [node]
 3: 0xbba90e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbbac87 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd76ea5  [node]
 6: 0xd77a2f  [node]
 7: 0xd8586b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd8942c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd57b0b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x10a02b0 v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1449379  [node]

pid 50 SIGABRT (signal 6) (core dumped)
Build with Vite failed! ❌

```

**Reply by ElMassimo** [reply, marked as answer]
> there's a `public/vite-dev` directory but no `public/vite`

Verify that `RAILS_ENV` is `production` when precompiling assets for the Docker image.

Vite Ruby will not create `public/vite-dev` if you are building for production.

**Comment by rockwellll** [comment]
I ran the `bin/vite build` command on dev and it successfully generated a `public/vite` directory

**Comment by rockwellll** [comment]
> Verify that `RAILS_ENV` is `production` when precompiling assets for the Docker image.
> 
> Vite Ruby will not create `public/vite-dev` if you are building for production.

Thanks for this note! Indeed, we were not running the command in production mode.

**Comment by andrer0cha** [comment]
Hey @ElMassimo, I'm facing a similar issue also on a docker image.
I have the `vite/` folder but it has only `assets/` and not `manifest` inside.

Also, my trace tells me the build was successful and that I'm running in production mode:
```
app-1  | Last build in production mode:
app-1  | {
app-1  |   "success": true,
app-1  |   "errors": "\n(!) Some chunks are larger than 500 kB after minification. Consider:\n- Using dynamic import() to code-split the application\n- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks\n- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.\n",
app-1  |   "timestamp": "2024-12-26 17:40:53",
app-1  |   "vite_ruby": "3.8.0",
app-1  |   "digest": "fcdcf1403e7223ff7b1e8a8f4a8d789fb91df915"
```

The docker server directory includes a `vite-dev/` folder as well and I already tried running `RAILS_ENV=production bin/rake vite:clobber` hoping to clean it but it didn't.

I might be making a noobie mistake here, it's my first time trying to set up a docker project.
Copying also the Dockerfile:
```dockerfile
FROM ruby:3.3-alpine
ENV BUNDLER_VERSION=2.5

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

# Update the package lists before installing.
RUN apk add --update --no-cache \
  binutils-gold \
  build-base \
  curl \
  file \
  g++ \
  gcc \
  git \
  less \
  libstdc++ \
  libffi-dev \
  libc-dev \ 
  linux-headers \
  libxml2-dev \
  libxslt-dev \
  libgcrypt-dev \
  make \
  netcat-openbsd \
  nodejs \
  openssl \
  pkgconfig \
  postgresql-dev \
  python3 \
  tzdata \
  nodejs-current \
  npm

ENV APP_HOME /usr/src/app
RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}

# Make sure we are running bundler version 2.5
RUN gem install bundler -v 2.5

# Copy the Gemfile
COPY Gemfile ${APP_HOME}/Gemfile
COPY Gemfile.lock ${APP_HOME}/Gemfile.lock

RUN bundle config build.nokogiri --use-system-libraries
RUN bundle check || bundle install

COPY package.json ${APP_HOME}

# Copy the project over
COPY . ${APP_HOME}

# Map port 8080 to the outside world (your local computer)
EXPOSE 8080

ENTRYPOINT ["./entrypoints/docker-entrypoint.sh"]
```

And the docker-compose for reference:
```yml
# docker-compose.yml
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/usr/src/app/node_modules
    env_file: .env
    environment:
      - RAILS_ENV=production # We are on Production now!
      - RAILS_SERVE_STATIC_FILES=true # Assets were already built by Dockerfile ;)
      - RAILS_LOG_TO_STDOUT=true # So we can see Rails logs with `docker compose logs` command
      - RAILS_MASTER_KEY=<MY_KEY>
      - REDIS_HOST=redis
  database:
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:latest
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app      
      - database
      - redis
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/usr/src/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
```

```yml
# docker-entrypoint.sh
#!/bin/sh

set -e

if [ -f tmp/pids/server.pid ]; then
  rm tmp/pids/server.pid
fi

RAILS_ENV=production bundle exec rake db:create
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production bundle exec rails assets:precompile
RAILS_ENV=production bundle exec rails s -b 0.0.0.0
```

I already tried running the `rails assets:precompile` inside the `Dockerfile` instead of having it in the `entrypoint` but it was not working.

Thank you!!
